# Strateg(P)ython Migration

## Load libraries

In [1]:
import json
import time

from mstrio.api import browsing
import yaml
import os
import tempfile
import pandas as pd
from time import sleep
from mstr_robotics.read_out_prj_obj import read_gen

from azure.storage.blob import BlobServiceClient

from mstrio.object_management import folder
from mstrio.object_management.migration import (
    PackageType,
    Migration,
    PackageConfig,
    PackageSettings
)

from mstrio.object_management.migration.package import (
    Action,
    ImportStatus,
    PackageStatus,
    ValidationStatus,
)


i_read_gen=read_gen()

from azure.storage.blob import BlobServiceClient
import os

def delete_mmp_files_in_folder(connection_string, container_name, folder_path):
    """
    Delete all .mmp files directly under a specific folder path in Azure Blob Storage.
    Does NOT delete files in subfolders.
    
    Args:
        connection_string: Azure storage connection string
        container_name: Container name (e.g., 'mstrmigrations')
        folder_path: Folder path (e.g., 'mstr/shared/migrations/packages/2025-12-16')
    
    Returns:
        dict with 'deleted_count', 'deleted_files', and 'errors' keys
    """
    try:
        # Create blob service client
        blob_service_client = BlobServiceClient.from_connection_string(connection_string)
        container_client = blob_service_client.get_container_client(container_name)
        
        # Ensure folder path ends with /
        if not folder_path.endswith('/'):
            folder_path = folder_path + '/'
        
        deleted_files = []
        errors = []
        
        # List all blobs with the folder prefix
        blob_list = container_client.list_blobs(name_starts_with=folder_path)
        
        for blob in blob_list:
            # Check if file is directly in the folder (not in subfolders)
            relative_path = blob.name[len(folder_path):]
            
            # Skip if it's in a subfolder (contains '/')
            if '/' in relative_path:
                continue
            
            # Check if it's an .mmp file
            if blob.name.endswith('.mmp'):
                try:
                    blob_client = blob_service_client.get_blob_client(
                        container=container_name,
                        blob=blob.name
                    )
                    blob_client.delete_blob()
                    deleted_files.append(blob.name)
                    #print(f"✓ Deleted: {blob.name}")
                except Exception as err:
                    errors.append({'file': blob.name, 'error': str(err)})
                    #print(f"✗ Failed to delete {blob.name}: {err}")
        
        return {
            'success': True,
            'deleted_count': len(deleted_files),
            'deleted_files': deleted_files,
            'errors': errors
        }
        
    except Exception as err:
        return {
            'success': False,
            'error': str(err)
        }

def bld_mig_list_from_excel(conn, excel_df,action= "USE_EXISTING",include_dependents= False ):

    #obj_l = get_folder_obj_l(conn=conn, folder_id=folder_id)
    guid_l=excel_df["object_guid"].to_list()
    obj_det_l=[]
    for guid in guid_l:
        obj_det_d = {}
        body={"projectIdAndObjectIds": [
              {"projectId": conn.project_id,
              "objectIds": [guid]
                }]  }
        obj_d=browsing.get_objects_from_quick_search(connection=conn,
                                             body=body).json()
        obj_det_d["id"] = obj_d["result"][0]["id"]
        obj_det_d["type"] = obj_d["result"][0]["type"]
        obj_det_d["action"] = action
        obj_det_d["include_dependents"] = include_dependents
        obj_det_d["subtype"] = obj_d["result"][0]["subtype"] # only for read out object definition (see end of note book)
        obj_det_l.append(obj_det_d.copy())  

    return obj_det_l

def move_blob_to_folder(connection_string, container_name, source_path, target_path):
    """
    Move a blob from one location to another within the same container.
    Creates target folder in the same parent directory as the source file.
    Deletes the source blob after successful copy.
    """
    try:
        # Create blob service client
        blob_service_client = BlobServiceClient.from_connection_string(connection_string)
        
        source_blob_client = blob_service_client.get_blob_client(
            container=container_name, 
            blob=source_path
        )
        
        # Get target blob client
        target_blob_client = blob_service_client.get_blob_client(
            container=container_name, 
            blob=target_path
        )
        
        # Copy blob (async operation)
        source_url = source_blob_client.url
        copy_operation = target_blob_client.start_copy_from_url(source_url)
        
        # Wait for copy to complete
        properties = target_blob_client.get_blob_properties()
        while properties.copy.status == 'pending':
            time.sleep(1)
            properties = target_blob_client.get_blob_properties()
        
        # Check if copy was successful
        if properties.copy.status == 'success':
            # Delete source blob after successful copy
            source_blob_client.delete_blob()
            
            return {
                'success': True,
                'source_path': source_path,
                'target_path': target_path,
                'operation': 'moved',
                'copy_operation' : copy_operation 


            }
        else:
            return {
                'success': False,
                'source_path': source_path,
                'error': f'Copy failed with status: {properties.copy.status}',
                'copy_operation' : copy_operation 
            }
        
    except Exception as err:
        return {
            'success': False,
            'source_path': source_path,
            'error': str(err),
            'copy_operation' : copy_operation 
        }
    
def bld_mig_list_from_sh_fold(conn, folder_id,action= "USE_EXISTING",include_dependents= False ):

    #obj_l = get_folder_obj_l(conn=conn, folder_id=folder_id)
    i_folder = folder.Folder(connection=conn, id=folder_id)
    obj_l = i_folder.get_contents(to_dictionary=True)
    
    obj_det_l=[]
    for obj_d in obj_l:
        #print(obj_d)
        if obj_d["type"] == 18:
            obj_det_d = {}
            obj_det_d["id"] = obj_d["target_info"]["id"]
            obj_det_d["type"] = obj_d["target_info"]["type"]
            obj_det_d["action"] = action
            obj_det_d["include_dependents"] = include_dependents
            obj_det_d["subtype"] = obj_d["target_info"]["subtype"] # only for read out object definition (see end of note book)
            obj_det_l.append(obj_det_d.copy())  

    return obj_det_l

## Set parameters

In [2]:
from mstrio.connection import Connection

migrations_excel_file="C:\\Users\\danie\\OneDrive\\Dokumente\\MSTR_ROBOTICS\\MigrationDemoUserGuppe.xlsx"
migrations_excel_df=pd.read_excel(migrations_excel_file)

with open('..\\config\\user_d.json', 'r') as openfile:
    user_d = json.load(openfile)

conn_params =  user_d["conn_params"]
source_conn = Connection(**conn_params)

with open("../config/dans_migrations.yml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

container_name = config['azure_storage']['container_name']
account_name = config['azure_storage']['account_name']
AccountKey = config['azure_storage']['account_key']
short_cut_folder_id = config['microstrategy']['short_cut_folder_id']
source_project_id = config['microstrategy']['source_project_id']
target_project_id = config['microstrategy']['target_project_id']
directory_path = config['directory']['path']

usr_migration_folder_name="Daniel_Migration"
usr_package_folder_name="usertreffen"

connection_string = f"DefaultEndpointsProtocol=https;AccountName={account_name};AccountKey={AccountKey};EndpointSuffix=core.windows.net"
migrations_excel_df

Connection to Strategy One Intelligence Server has been established.
No project selected.

  object_name                       object_guid
0  OSI_Report  9FA9FE43484C9640188B2D89DBD4C612
1      Region  8D679D4B11D3E4981000E787EC6DE8A4

## Configure Migration

In [3]:
package_settings = PackageSettings(
    Action.FORCE_REPLACE,
    PackageSettings.UpdateSchema.RECAL_TABLE_LOGICAL_SIZE,
    PackageSettings.AclOnReplacingObjects.REPLACE,
    PackageSettings.AclOnNewObjects.KEEP_ACL_AS_SOURCE_OBJECT,
)

## Connect to projects

In [4]:
conn_params["project_id"]=source_project_id
source_conn = Connection(**conn_params)
conn_params["project_id"]=target_project_id
target_conn = Connection(**conn_params)
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

Connection to Strategy One Intelligence Server has been established.
Connection to Strategy One Intelligence Server has been established.

## Create package

In [5]:
package_content_info=bld_mig_list_from_excel(conn=source_conn, excel_df=migrations_excel_df,action= "FORCE_REPLACE",include_dependents= False)
package_config = PackageConfig(
    package_settings,  package_content_info # [ package_content_from_object]
)

my_obj_mig = Migration.create_object_migration(
    connection=source_conn,
    toc_view=package_config,
    name=usr_package_folder_name,
    project_id=source_conn.project_id,
)

while my_obj_mig.package_info.status == PackageStatus.CREATING:
    sleep(2)
    my_obj_mig.fetch()

my_obj_mig.package_info.status

Successfully started creation of migration object with ID: '1B03C2A5E62D444B8F737EE88714797B:C8CF0AD1C5BA4982BC6070CD202E00DC'

PackageStatus.CREATED

In [6]:
package_content_info

[{'id': '9FA9FE43484C9640188B2D89DBD4C612',
  'type': 3,
  'action': 'FORCE_REPLACE',
  'include_dependents': False,
  'subtype': 768},
 {'id': '8D679D4B11D3E4981000E787EC6DE8A4',
  'type': 12,
  'action': 'FORCE_REPLACE',
  'include_dependents': False,
  'subtype': 3072}]

## Validate Package

In [7]:
# Check migration validation status
my_obj_mig.trigger_validation(
    target_env=target_conn, target_project_name=target_conn.project_name
)

while my_obj_mig.validation.status == ValidationStatus.VALIDATING:
    sleep(2)
    my_obj_mig.fetch()

print(my_obj_mig.validation)

Successfully triggered validation process for migration with ID: '1B03C2A5E62D444B8F737EE88714797B:C8CF0AD1C5BA4982BC6070CD202E00DC'
Validation(status=ValidationStatus.VALIDATED, progress=100.0, message='Success', creation_date=datetime.datetime(2026, 6, 21, 6, 38, 32, tzinfo=datetime.timezone.utc), last_update_date=None)

## Move Migration Pack to migration folder

In [8]:
source_path=my_obj_mig.package_info.storage.path
file_name = os.path.basename(source_path)
parent_dir = os.path.dirname(source_path)

# Build target path in the same parent directory
target_path = f"{parent_dir}/{usr_package_folder_name}/{file_name}"
target_folder_name=usr_package_folder_name

move_blob_to_folder(connection_string, container_name
                    , source_path, target_path)

{'success': True,
 'source_path': 'mstr/shared/migrations/packages/2026-06-21/00F217F40B8649039B22B160CFBC49D6.mmp',
 'target_path': 'mstr/shared/migrations/packages/2026-06-21/usertreffen/00F217F40B8649039B22B160CFBC49D6.mmp',
 'operation': 'moved',
 'copy_operation': {'etag': '"0x8DECF5FBAFB54F2"',
  'last_modified': datetime.datetime(2026, 6, 21, 6, 38, 39, tzinfo=datetime.timezone.utc),
  'client_request_id': 'd676d2e8-6d3b-11f1-87d4-2c9c5850f942',
  'request_id': 'd50bfb32-d01e-0076-5648-0147a9000000',
  'version': '2025-11-05',
  'version_id': None,
  'date': datetime.datetime(2026, 6, 21, 6, 38, 39, tzinfo=datetime.timezone.utc),
  'copy_id': '0d3f5f93-8384-4bad-b563-a7b988bf7d81',
  'copy_status': 'success'}}


## Trigger migration

In [9]:
blob_client = blob_service_client.get_blob_client(
# Get blob client
    container=container_name,
    blob=target_path
)

# Download to temporary file
with tempfile.NamedTemporaryFile(delete=False, suffix='.mmp') as tmp_file:
    download_stream = blob_client.download_blob()
    tmp_file.write(download_stream.readall())
    temp_file_path = tmp_file.name

# Now use the temporary file with migrate_from_file
from_file_mig = Migration.migrate_from_file(
    connection=target_conn,
    file_path=temp_file_path,
    package_type=PackageType.OBJECT,
    name="object_mig_from_azure_storage",
    target_project_name=target_conn.project_name
)
while from_file_mig.import_info.status == ImportStatus.IMPORTING:
    sleep(2)
    from_file_mig.fetch()

from_file_mig.import_info.status

Successfully started migration from file with ID: '751FF498020448589A198390BDB90258:1E7F8E30837A4455A776822E097DB645'.

ImportStatus.IMPORTED

In [10]:
mstr_migration_dir = os.path.dirname(my_obj_mig.package_info.storage.path)
mstr_migration_dir

'mstr/shared/migrations/packages/2026-06-21'

## Archive Migration

### move undo mmp file to migration folder

In [11]:
source_path= from_file_mig.import_info.undo_storage.path
file_name = os.path.basename(source_path)
target_path = f"{parent_dir}/{usr_package_folder_name}/undo.mmp"
move_blob_to_folder(connection_string, container_name, source_path, target_path)

{'success': True,
 'source_path': 'mstr/shared/migrations/undo/751FF498020448589A198390BDB90258/1E7F8E30837A4455A776822E097DB645.mmp',
 'target_path': 'mstr/shared/migrations/packages/2026-06-21/usertreffen/undo.mmp',
 'operation': 'moved',
 'copy_operation': {'etag': '"0x8DECF5FBF995A4C"',
  'last_modified': datetime.datetime(2026, 6, 21, 6, 38, 47, tzinfo=datetime.timezone.utc),
  'client_request_id': 'db157a87-6d3b-11f1-a2f9-2c9c5850f942',
  'request_id': '4858c467-401e-0039-3048-0136fd000000',
  'version': '2025-11-05',
  'version_id': None,
  'date': datetime.datetime(2026, 6, 21, 6, 38, 47, tzinfo=datetime.timezone.utc),
  'copy_id': 'e08825f7-09ab-4701-80f6-217d21084f19',
  'copy_status': 'success'}}

### store migrated objects to CSV file

In [12]:
# Store migrated objects to CSV file at target path
package_content_df = pd.DataFrame(package_content_info)

# Build target path for CSV
csv_target_path = f"{parent_dir}/{target_folder_name}/package_content.csv"

# Create blob client for CSV
csv_blob_client = blob_service_client.get_blob_client(
    container=container_name,
    blob=csv_target_path
)

# Convert DataFrame to CSV string
csv_data = package_content_df.to_csv(index=False)

# Upload CSV to Azure Blob Storage
csv_blob_client.upload_blob(csv_data, overwrite=True)

print(f"CSV saved to: {csv_target_path}")
package_content_df

CSV saved to: mstr/shared/migrations/packages/2026-06-21/usertreffen/package_content.csv

,id,type,action,include_dependents,subtype
0,9FA9FE43484C9640188B2D89DBD4C612,3,FORCE_REPLACE,False,768
1,8D679D4B11D3E4981000E787EC6DE8A4,12,FORCE_REPLACE,False,3072

### save package & migration files

In [13]:

# Get source path and build target directory
source_path = my_obj_mig.package_info.storage.path

package_info_path = f"{parent_dir}/{target_folder_name}/package_info.txt"
package_info_blob = blob_service_client.get_blob_client(container=container_name, blob=package_info_path)
package_info_blob.upload_blob(str(my_obj_mig.package_info), overwrite=True)
print(f"✓ Uploaded: {package_info_path}")

# Upload migration_info.txt
migration_info_path = f"{parent_dir}/{target_folder_name}/migration_info.txt"
migration_info_blob = blob_service_client.get_blob_client(container=container_name, blob=migration_info_path)
migration_info_blob.upload_blob(str(from_file_mig.import_info), overwrite=True)
print(f"✓ Uploaded: {migration_info_path}")

✓ Uploaded: mstr/shared/migrations/packages/2026-06-21/usertreffen/package_info.txt
✓ Uploaded: mstr/shared/migrations/packages/2026-06-21/usertreffen/migration_info.txt

## Read & Store Object definition

In [14]:
# Get source path and build target directory
source_path = my_obj_mig.package_info.storage.path
parent_dir = os.path.dirname(source_path)

# Create blob service client
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# Build target path for object_def.json
obj_def_target_path = f"{parent_dir}/{target_folder_name}/object_def.json"

# Get blob client
obj_def_blob = blob_service_client.get_blob_client(
    container=container_name,
    blob=obj_def_target_path
)

obj_def_l=[]
for obj in package_content_info:
    obj_def=i_read_gen.get_obj_def(conn=source_conn,object_id=obj["id"],obj_type=obj["type"],obj_sub_type=obj["subtype"])
    obj_def_l.append(obj_def)


# Upload object definition JSON
# If obj_def_l is already a list of dicts, convert to JSON string
obj_def_json_str = json.dumps(obj_def_l, indent=2)
obj_def_blob.upload_blob(obj_def_json_str, overwrite=True)

print(f"✓ Uploaded: {obj_def_target_path}")

✓ Uploaded: mstr/shared/migrations/packages/2026-06-21/usertreffen/object_def.json

In [15]:
source_conn.close()
target_conn.close()

Connection to Strategy One Intelligence Server has been closed.
Connection to Strategy One Intelligence Server has been closed.